### ISSUE TITLE
[BUG] app crashes on OSC start.

### ISSUE THREAD

**Issue by cglenn1103** [maeganwilson/iHog4#42]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maeganwilson** [comment]
@cglenn1103 does the app crash on OSC start from the console or from the app?

**Comment by cglenn1103** [comment]
The console.

**Comment by maeganwilson** [comment]
What version of software are you running on the console?
Do you have OSC enabled on the app before you turn on OSC out on the console?

What is the version of iHog?

**Comment by cglenn1103** [comment]
Console is 3.14.0
App is 2021.2

**Comment by cglenn1103** [comment]
As soon as I click "enable outgoing" on the console the app crashes. If I
disable I can open the app again.

**Comment by maeganwilson** [comment]
Which console are you on? I'm usually testing with Hog 4 PC. Also, which device are you using?

I'm trying to reproduce the issue to see if I can get it to occur, but I can't right now.

**Comment by cglenn1103** [comment]
Its hog 4 pc with a hoglet  and I'm using an iphone 12.

**Comment by maeganwilson** [comment]
Thanks! I should be pushing out an update soon that might address this issue. It has a little bit of re-work done to the connection side.

**Comment by maeganwilson** [comment]
I think I got this working in 2021.3. Should be out in the next week
